clubhub/home/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import Length


class FeedbackForm(FlaskForm):
    text = TextAreaField('', validators=[Length(max=4000)])
    submit = SubmitField()

clubhub/home/__init__.py
from flask import Blueprint

home = Blueprint(
    'home', __name__,
    template_folder='templates', static_folder='static')

from . import views

clubhub/home/views.py
import os

from flask import render_template, redirect, url_for, flash
from flask_login import current_user, login_required

from clubhub.models import Club, Company
from clubhub.email import send_email
from clubhub.utils import parse_arg
from clubhub.utils.club import get_my_clubs, get_clubs_to_admin, get_club_roles
from clubhub.utils.membership import get_active_memberships
from clubhub.utils.company import get_company_roles, get_companies_to_admin
from . import home
from .forms import FeedbackForm


@home.route('/')
def index():
    if current_user.is_authenticated:
        my_clubs = get_my_clubs(current_user)
        my_clubs_to_admin = get_clubs_to_admin(current_user)
        my_companies_to_admin = get_companies_to_admin(current_user)
    else:
        my_clubs = None
        my_clubs_to_admin = None
        my_companies_to_admin = None
    context = {
        'my_clubs': my_clubs,
        'my_clubs_to_admin': my_clubs_to_admin,
        'my_companies_to_admin': my_companies_to_admin
    }
    return render_template('home/index.html', context=context)


@home.route('/about')
def about():
    return render_template('home/about.html')


@home.route('/user_guide')
def user_guide():
    return render_template('home/user_guide.html')


@home.route('/privacy_policy')
def privacy_policy():
    return render_template('home/privacy_policy.html')


@home.route('/feedback', methods=['GET', 'POST'])
def feedback():
    form = FeedbackForm()
    if form.validate_on_submit():
        user = current_user if current_user.is_authenticated else None
        text = form.text.data
        if send_email(os.environ.get('FEEDBACK_EMAIL'), 'User Feedback',
                      'home/email/feedback', user=user, text=text):
            flash('Thanks for your feedback!')
        return redirect(url_for('home.feedback'))
    return render_template('home/feedback.html', form=form)


@home.route('/menu-my-club')
@login_required
def menu_my_club():
    club_id = parse_arg('club_id', int)
    club = Club.query.get_or_404(club_id)
    memberships = get_active_memberships(current_user, club)
    context = {
        'club': club,
        'memberships': memberships,
    }
    return render_template('home/menu_my_club.html', context=context)


@home.route('/menu-club-administration')
@login_required
def menu_club_administration():
    club_id = parse_arg('club_id', int)
    club = Club.query.get_or_404(club_id)
    roles = get_club_roles(current_user, club)
    context = {
        'club': club,
        'roles': ", ".join(roles),
    }
    return render_template(
        'home/menu_club_administration.html', context=context)


@home.route('/menu-company-administration')
@login_required
def menu_company_administration():
    company_id = parse_arg('company_id', int)
    company = Company.query.get_or_404(company_id)
    roles = get_company_roles(current_user, company)
    context = {
        'company': company,
        'roles': ", ".join(roles),
    }
    return render_template(
        'home/menu_company_administration.html', context=context)

clubhub/home/templates/home/about.html
{% extends "base.html" %}

{% block page_title %}About{% endblock %}

{% block page_body %}
  <p>This website was created by Artur Scholz and Marcos Garcia Chillon.</p>
  <p>Based on the <a href="http://flask.pocoo.org/" target="_blank">Flask</a>, a Python web framework.</p>
  <p>The source code can be found <a href="https://gitlab.com/artur-scholz/clubhub" target="_blank">here</a>.</p>
{% endblock page_body %}

clubhub/home/templates/home/feedback.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %}Feedback{% endblock %}

{% block page_body %}
  <div>
    <p>
      Please provide feedback if you found a bug or have any kind of suggestion
      on how to improve this website. Note however that work is done on a
      best effort basis, so please be patient. And be as descriptive as possible.
    </p>
    <p>We keep track of issues <a href="https://gitlab.com/artur-scholz/clubhub/issues" target="_blank">here</a>.</p>
  </div>
  <br>
  {{ wtf.quick_form(form) }}
  <br>
{% endblock page_body %}

clubhub/home/templates/home/index.html
{% extends "base.html" %}

{% block page_title %}
  {% if not current_user.is_authenticated %}
    <img class="img-responsive center-block" src='static/img/home.png'>
  {% else %}
  {% endif %}
{% endblock page_title %}

{% block page_body %}
  {% if not current_user.is_authenticated %}
    <a class="btn btn-primary btn-block" href={{ url_for('auth.login') }} role="button">Login</a>
    <a class="btn btn-warning btn-block" href={{ url_for('auth.register') }} role="button">Register</a>
    <a class="btn btn-info btn-block" href={{ url_for('home.user_guide') }} role="button">Help</a>
  {% else %}
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Membership</strong></div>
      <div class="panel-body">
        {% if context.my_clubs %}
          {% for my_club in context.my_clubs %}
            <a class="btn btn-primary btn-block" href={{ url_for('home.menu_my_club', club_id=my_club.id) }} role="button">{{ my_club.name }}</a>
          {% endfor %}
        {% endif %}
        <a class="btn btn-warning btn-block" href={{ url_for('membership.request_membership') }} role="button">New</a>
      </div>
    </div>

    {% if context.my_clubs_to_admin %}
      <div class="panel panel-default">
        <div class="panel-heading"><strong>Club Administration</strong></div>
        <div class="panel-body">
          {% for my_club_to_admin in context.my_clubs_to_admin %}
            <a class="btn btn-primary btn-block" href={{ url_for('home.menu_club_administration', club_id=my_club_to_admin.id) }} role="button">{{ my_club_to_admin.name }}</a>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    {% if context.my_companies_to_admin %}
      <div class="panel panel-default">
        <div class="panel-heading"><strong>Company Administration</strong></div>
        <div class="panel-body">
          {% for my_company_to_admin in context.my_companies_to_admin %}
            <a class="btn btn-primary btn-block" href={{ url_for('home.menu_company_administration', company_id=my_company_to_admin.id) }} role="button">{{ my_company_to_admin.name }}</a>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endif %}
{% endblock page_body %}

clubhub/home/templates/home/menu_club_administration.html
{% extends "base.html" %}

{% block page_title %}{{ context.club.name }} Club Administration{% endblock %}

{% block page_body %}
  <p class="text-center">Role: {{ context.roles }}</p>
  <br>
  <a class="btn btn-primary btn-block" href={{ url_for('membership.list_members', club_id=context.club.id) }} role="button">Active Members</a>
  <a class="btn btn-primary btn-block" href={{ url_for('membership.list_memberships', club_id=context.club.id) }} role="button">Memberships History</a>
  <a class="btn btn-primary btn-block" href={{ url_for('membership.list_membership_requests', club_id=context.club.id) }} role="button">Pending Memberships</a>
  <a class="btn btn-warning btn-block" href={{ url_for('membership.create_membership', club_id=context.club.id) }} role="button">Create Membership</a>
  <a class="btn btn-primary btn-block" href={{ url_for('club.details_club', club_id=context.club.id) }} role="button">Club Info</a>
  <a class="btn btn-warning btn-block" href={{ url_for('club.update_club', club_id=context.club.id) }} role="button">Update Club Info</a>
  <br>
{% endblock page_body %}

clubhub/home/templates/home/menu_company_administration.html
{% extends "base.html" %}

{% block page_title %}{{ context.company.name }} Administration{% endblock %}

{% block page_body %}
  <p class="text-center">Role: {{ context.roles }}</p>
  <br>
  <a class="btn btn-primary btn-block" href={{ url_for('company.list_employees', company_id=context.company.id) }} role="button">List Employees</a>
  <a class="btn btn-primary btn-block" href={{ url_for('company.details_company', company_id=context.company.id) }} role="button">Company Info</a>
  <a class="btn btn-warning btn-block" href={{ url_for('company.update_company', company_id=context.company.id) }} role="button">Update Company Info</a>
  <br>
{% endblock page_body %}

clubhub/home/templates/home/menu_my_club.html
{% extends "base.html" %}

{% block page_title %}{{ context.club.name }} Club Membership{% endblock %}

{% block page_body %}
  {% for membership in context.memberships %}
    <p class="text-center">Membership from {{ membership.valid_from }} to {{ membership.valid_till }}</p>
  {% endfor %}
  <br>
  <a class="btn btn-warning btn-block" href={{ url_for('membership.request_membership', club_id=context.club.id) }} role="button">Renew Membership</a>
  <a class="btn btn-primary btn-block" href={{ url_for('club.details_club', club_id=context.club.id) }} role="button">Club Info</a>
  <br>
{% endblock page_body %}

clubhub/home/templates/home/privacy_policy.html
{% extends "base.html" %}

{% block page_title %}Terms and Privacy Policy{% endblock %}

{% block page_body %}
  <h5><b>Basic Terms</b></h5>
  <ol>
    <li>You must be at least 16 years old to use this page.</li>
    <li>You are responsible for any activity that occurs through your account.</li>
    <li>You are responsible for keeping your password secret and secure.</li>
    <li>We reserve the right to remove registered users in case they do not comply with the rules and code of conduct of the SSCC.</li>
  </ol>

  <h5><b>Privacy Policy</b></h5>
  <p>
    This page is used to inform website visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our MySSCC Club Service.<br/>
    If you choose to use our Service, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.
  </p>

  <h5><b>Information Collection</b></h5>
  <p>
    The Service collects the bare minimum personal information required by the SSCC, the related clubs and the companies to manage their subscriptions and members. This information includes name, email, password, company affiliation and spouse (if applicable). Other information may be requested on optional basis.</br>
    You are free to access and modify your information at any moment. In case you want to be totally removed from our system, we can anonymize  your personal data on request, using the <a href="{{ url_for('home.feedback') }}">contact form</a>.
  </p>

  <h5><b>Use and Sharing of Collected Information</b></h5>
  <p>
    The personal information you provide is used mainly for the following entities:
    <ol>
      <li>Club Administrators: Process your membership and maintain the list of club members. Club Administrators may share your personal information with external providers as part of the club activities (e.g. hotel room reservations).</li>
      <li>Companies Representatives: List and review the list of users registered under the company responsibility.</li>
      <li>SSCC Administrators: Produce reports for Insurance and Inventory purposes, and to monitor club membership.</li>
    </ol>
  </p>

  <h5><b>Cookies</b></h5>
  <p>
    Cookies are files with small amount of data that is commonly used an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer’s hard drive.<br/>
    Our website uses these “cookies” mainly for the purpose of tracking using authentication and to improve our Service. You have the option to either accept or refuse these cookies, and know when a cookie is being sent to your computer. If you choose to refuse our cookies, you may not be able to use some portions of our Service.
  </p>

  <h5><b>Links to Other Sites</b></h5>
  <p>
    Our Service may contain links to other sites (e.g. club webpages). If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites, visit us. We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
  </p>

  <h5><b>Changes to these Terms and Privacy Policy</b></h5>
  <p>
    We may update our Terms and Privacy Policy from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.
  </p>

  <h5><b>Contact Us</b></h5>
  <p>
    If you have any questions or suggestions about our Privacy Policy, do not hesitate to <a href="{{ url_for('home.feedback') }}">contact us</a>.
  </p>
{% endblock page_body %}

clubhub/home/templates/home/user_guide.html
{% extends "base.html" %}

{% block page_title %}User Guide{% endblock %}

{% block page_body %}
  <h5><b>Registration</b></h5>
  <p>
    Every user of this website needs to create an individual account through
    <a href={{ url_for('auth.register') }}>registration</a>. That is, you can NOT
    manage memberships for other people. Due to German law, you must be at least
    16 years old to register. Thus, your kids are not allowed to register. Their
    club memberships must be managed outside of this website (that is, directly
    with SSCC).
  </p>
  <p>
    To register, you need to supply an email address. This email address will
    be the only way to identify your user account. You may choose private or company
    email, but make sure it's an email account that is conveniently  accessible
    to you, as all information will be sent to this account. But don't worry,
    you can change your email at any time.
  </p>
  <p>
    After registration you will be asked to define your affiliation. If you work
    for ESA/EUMETSAT then please specify the company you are employed at. If you
    want to register as family  member (partner or child), then don’t select a
    company, but instead provide the email of your family member (that works
    for ESA/EUMETSAT) that he/she used to register at this website.
  </p>
  <p>
    On the other hand, if you select *Affiliates* from the company list because
    you are neither connected via work or family to ESOC/EUMETSAT then please
    fill out the *About me* section in your account to explain your affiliation.
  </p>
  <p>
    If you are connected via work in some way but your Company is not listed,
    please use the feedback form to let us know.
  </p>

  <h5><b>Memberships</b></h5>
  <p>
    As a registered user you can inform yourself about all the clubs
    <a href={{ url_for('club.list_all_clubs') }}>here</a>. Go to the details
    of each club to learn about their membership rules. Usually it is a good
    idea to first get in touch with the club chairman etc. beforehand, outside
    of this website, to learn more on their membership procedure.
  </p>
  <p>
    When this is settled then <a href={{ url_for('membership.request_membership') }}>request membership</a>
    in order to create a register a membership within this website. This information
    about your memberships is visibly to you, the club administration of your club,
    and to the SSCC committee.
  </p>

  <h5><b>Club Administration</b></h5>
  <p>
    As a club administrator (i.e. chairman/sectretary/treasurer/inventory) you can:
    <ul>
      <li>see a list of current club members,</li>
      <li>see current active memberships,</li>
      <li>manage memberships (create, modify, delete),</li>
      <li>and update club information.</li>
  </ul>
  </p>
  <p>
    If, after your annual club meeting, the administration has changed, you
    simply enter this information in the club details by updating the current
    board of club administrators. For this, you need to enter the user email
    of the new board into the relevant roles.
  </p>
{% endblock page_body %}